import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.0.0/firebase-app.js';
import { getAuth, GoogleAuthProvider, onAuthStateChanged, signInWithRedirect, signOut } from 'https://www.gstatic.com/firebasejs/12.0.0/firebase-auth.js';
import { getFirestore, doc, getDoc, setDoc } from 'https://www.gstatic.com/firebasejs/12.0.0/firebase-firestore.js';
const app=initializeApp({apiKey:'AIzaSyB2zhIwPhxG2mVvU6RTGLoHIDOwiIJLDZQ',authDomain:'allinone-96e4f.firebaseapp.com',projectId:'allinone-96e4f',storageBucket:'allinone-96e4f.firebasestorage.app',messagingSenderId:'238276487927',appId:'1:238276487927:web:c1d682a638cba88e5681f2'}),auth=getAuth(app),db=getFirestore(app);
const keys=['kanban-tasks-v2','kanban-categories-v1','kanban-reports-v1','kanban-reflections-v1','study-plus-local-v1','habit-tracker-v1','habit-weekly-order-v1','habit-mini-order-v1','habit-streak-metric-v1','habit-calendar-view-v1','kanban-deleted-tasks-v1','kanban-task-archive-v1'];let user=null,last='';
const read=()=>Object.fromEntries(keys.filter(k=>localStorage.getItem(k)!==null).map(k=>[k,localStorage.getItem(k)]));
async function sync(){if(!user)return;const ref=doc(db,'users',user.uid),snap=await getDoc(ref),local=read();if(snap.exists()&&snap.data().appData){Object.entries(snap.data().appData).forEach(([k,v])=>keys.includes(k)&&localStorage.setItem(k,v));window.dispatchEvent(new Event('storage'));last=JSON.stringify(read())}else{await setDoc(ref,{appData:local,updatedAt:Date.now()},{merge:true});last=JSON.stringify(local)}}
async function upload(){if(!user)return;const data=read(),next=JSON.stringify(data);if(next!==last){await setDoc(doc(db,'users',user.uid),{appData:data,updatedAt:Date.now()},{merge:true});last=next}}
function button(){if(document.getElementById('firebaseAuthButton'))return;const b=document.createElement('button');b.id='firebaseAuthButton';b.type='button';b.style.cssText='position:fixed;top:16px;right:18px;z-index:10000;border:0;border-radius:999px;padding:8px 13px;background:#fff;box-shadow:0 4px 16px #0001;color:#3b403d;font:inherit;font-size:12px;cursor:pointer';b.onclick=()=>user?confirm('ログアウトしますか？')&&signOut(auth):signInWithRedirect(auth,new GoogleAuthProvider());document.body.append(b)}
onAuthStateChanged(auth,async u=>{user=u;button();const b=document.getElementById('firebaseAuthButton');b.textContent=u?`${u.displayName||'ログイン中'} ⌄`:'Googleでログイン';if(u)await sync()});setInterval(upload,2500);
